services:
  db:
    container_name: student_hub_api_postgres
    image: postgres:17.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: student_hub_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - student_hub_api_db:/var/lib/postgresql/data
    networks:
      - student_hub_api_network
    ports:
      - "5432:5432"

  pgadmin:
    container_name: student_hub_api_pgadmin
    image: dpage/pgadmin4:8.4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: kykyrizky57@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - student_hub_api_network
    ports:
      - 8082:80

networks:
  student_hub_api_network:
    driver: bridge

volumes:
  student_hub_api_db:
